name: schedule

on:
  push:  # push 이벤트
  workflow_dispatch:  # 수동 실행 이벤트
  schedule:
    - cron: '30 * * * *'  # 매 정각 15분마다 실행

jobs:
  make-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write  # 이슈 작성 권한
    
    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v4

      - name: 노드 셋업
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: index.js 실행
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node index.js
